import * as stylex from "@stylexjs/stylex";

type AppearancePalette = Record<string, string>;

export const appearancePalette: Record<"light" | "dark", AppearancePalette> = {
  light: {
    canvas: "#F2F6FB",
    canvasRaised: "#F8FAFD",
    surface: "#FFFFFF",
    surfaceSoft: "rgba(255, 255, 255, 0.54)",
    surfaceStrong: "#E4ECF4",
    ink: "#0B1320",
    body: "#344054",
    muted: "#5C6675",
    subtle: "#7C8899",
    border: "#CBD6E2",
    borderStrong: "#AEBBD0",
    primary: "#0067D9",
    primaryHover: "#0056B4",
    primaryPressed: "#004C9E",
    primarySoft: "rgba(0, 103, 217, 0.10)",
    primarySoftHover: "rgba(0, 103, 217, 0.16)",
    onPrimary: "#FFFFFF",
    success: "#087D5B",
    successSoft: "#DFF6ED",
    danger: "#C7253E",
    dangerHover: "#A91D34",
    dangerSoft: "#FFF0F3",
    dangerSoftHover: "#FFE1E7",
    dangerOnDark: "#C7253E",
    dangerOnDarkSoft: "rgba(199, 37, 62, 0.12)",
    warning: "#8A5000",
    warningHover: "#713F00",
    warningSoft: "#FFF5DC",
    warningSoftHover: "#FFE9B4",
    dark: "#0B0E14",
    darkRaised: "#111722",
    onDark: "#F5F7FB",
    onDarkMuted: "#AAB4C2",
    focus: "#0067D9",
    canvasAmbient:
      "radial-gradient(circle at 14% 0%, rgba(82, 168, 255, 0.13), transparent 32%), radial-gradient(circle at 88% 10%, rgba(155, 180, 210, 0.18), transparent 30%), #F2F6FB",
    glassSubtle: "rgba(255, 255, 255, 0.48)",
    glassChrome: "rgba(248, 251, 255, 0.64)",
    glassOverlay: "rgba(250, 252, 255, 0.82)",
    glassFallback: "#F8FAFD",
    glassBorder: "rgba(77, 112, 160, 0.22)",
    glassHighlight: "rgba(255, 255, 255, 0.78)",
    scrim: "rgba(11, 20, 40, 0.48)",
    userBubble: "rgba(220, 235, 255, 0.88)",
    userBubbleBorder: "rgba(0, 103, 217, 0.16)",
  },
  dark: {
    canvas: "#0B0E14",
    canvasRaised: "#111722",
    surface: "#131C28",
    surfaceSoft: "rgba(19, 28, 40, 0.62)",
    surfaceStrong: "#243244",
    ink: "#F5F7FB",
    body: "#D2D9E3",
    muted: "#AAB4C2",
    subtle: "#8A96A8",
    border: "#2E3A4D",
    borderStrong: "#3E4E63",
    primary: "#52A8FF",
    primaryHover: "#6FB8FF",
    primaryPressed: "#3D95F5",
    primarySoft: "rgba(82, 168, 255, 0.14)",
    primarySoftHover: "rgba(82, 168, 255, 0.22)",
    onPrimary: "#07111F",
    success: "#4DD6A8",
    successSoft: "rgba(77, 214, 168, 0.14)",
    danger: "#FF6B81",
    dangerHover: "#FF8A9B",
    dangerSoft: "rgba(255, 107, 129, 0.13)",
    dangerSoftHover: "rgba(255, 107, 129, 0.22)",
    dangerOnDark: "#FF8A9B",
    dangerOnDarkSoft: "rgba(255, 107, 129, 0.16)",
    warning: "#F5B94C",
    warningHover: "#FFCA68",
    warningSoft: "rgba(245, 185, 76, 0.14)",
    warningSoftHover: "rgba(245, 185, 76, 0.22)",
    dark: "#0B0E14",
    darkRaised: "#131C28",
    onDark: "#F5F7FB",
    onDarkMuted: "#AAB4C2",
    focus: "#52A8FF",
    canvasAmbient:
      "radial-gradient(circle at 12% 0%, rgba(82, 168, 255, 0.16), transparent 34%), radial-gradient(circle at 88% 8%, rgba(75, 105, 140, 0.18), transparent 30%), #0B0E14",
    glassSubtle: "rgba(16, 24, 34, 0.48)",
    glassChrome: "rgba(15, 23, 33, 0.64)",
    glassOverlay: "rgba(13, 21, 31, 0.82)",
    glassFallback: "#131C28",
    glassBorder: "rgba(255, 255, 255, 0.14)",
    glassHighlight: "rgba(255, 255, 255, 0.18)",
    scrim: "rgba(0, 0, 0, 0.58)",
    userBubble: "rgba(82, 168, 255, 0.14)",
    userBubbleBorder: "rgba(82, 168, 255, 0.28)",
  },
};

const light = appearancePalette.light;
const dark = appearancePalette.dark;

export const colors = stylex.defineVars({
  canvas: light.canvas,
  canvasRaised: light.canvasRaised,
  surface: light.surface,
  surfaceSoft: light.surfaceSoft,
  surfaceStrong: light.surfaceStrong,
  ink: light.ink,
  body: light.body,
  muted: light.muted,
  subtle: light.subtle,
  border: light.border,
  borderStrong: light.borderStrong,
  primary: light.primary,
  primaryHover: light.primaryHover,
  primaryPressed: light.primaryPressed,
  primarySoft: light.primarySoft,
  primarySoftHover: light.primarySoftHover,
  onPrimary: light.onPrimary,
  success: light.success,
  successSoft: light.successSoft,
  danger: light.danger,
  dangerHover: light.dangerHover,
  dangerSoft: light.dangerSoft,
  dangerSoftHover: light.dangerSoftHover,
  dangerOnDark: light.dangerOnDark,
  dangerOnDarkSoft: light.dangerOnDarkSoft,
  warning: light.warning,
  warningHover: light.warningHover,
  warningSoft: light.warningSoft,
  warningSoftHover: light.warningSoftHover,
  dark: light.dark,
  darkRaised: light.darkRaised,
  onDark: light.onDark,
  onDarkMuted: light.onDarkMuted,
  focus: light.focus,
  canvasAmbient: light.canvasAmbient,
  glassSubtle: {
    default: light.glassSubtle,
    "@supports not (backdrop-filter: blur(1px))": light.glassFallback,
    "@media (prefers-reduced-transparency: reduce)": light.glassFallback,
  },
  glassChrome: {
    default: light.glassChrome,
    "@supports not (backdrop-filter: blur(1px))": light.glassFallback,
    "@media (prefers-reduced-transparency: reduce)": light.glassFallback,
  },
  glassOverlay: {
    default: light.glassOverlay,
    "@supports not (backdrop-filter: blur(1px))": light.glassFallback,
    "@media (prefers-reduced-transparency: reduce)": light.glassFallback,
  },
  glassFallback: light.glassFallback,
  glassBorder: light.glassBorder,
  glassHighlight: light.glassHighlight,
  scrim: light.scrim,
  userBubble: light.userBubble,
  userBubbleBorder: light.userBubbleBorder,
});

export const darkColorsTheme = stylex.createTheme(colors, {
  canvas: dark.canvas,
  canvasRaised: dark.canvasRaised,
  surface: dark.surface,
  surfaceSoft: dark.surfaceSoft,
  surfaceStrong: dark.surfaceStrong,
  ink: dark.ink,
  body: dark.body,
  muted: dark.muted,
  subtle: dark.subtle,
  border: dark.border,
  borderStrong: dark.borderStrong,
  primary: dark.primary,
  primaryHover: dark.primaryHover,
  primaryPressed: dark.primaryPressed,
  primarySoft: dark.primarySoft,
  primarySoftHover: dark.primarySoftHover,
  onPrimary: dark.onPrimary,
  success: dark.success,
  successSoft: dark.successSoft,
  danger: dark.danger,
  dangerHover: dark.dangerHover,
  dangerSoft: dark.dangerSoft,
  dangerSoftHover: dark.dangerSoftHover,
  dangerOnDark: dark.dangerOnDark,
  dangerOnDarkSoft: dark.dangerOnDarkSoft,
  warning: dark.warning,
  warningHover: dark.warningHover,
  warningSoft: dark.warningSoft,
  warningSoftHover: dark.warningSoftHover,
  dark: dark.dark,
  darkRaised: dark.darkRaised,
  onDark: dark.onDark,
  onDarkMuted: dark.onDarkMuted,
  focus: dark.focus,
  canvasAmbient: dark.canvasAmbient,
  glassSubtle: {
    default: dark.glassSubtle,
    "@supports not (backdrop-filter: blur(1px))": dark.glassFallback,
    "@media (prefers-reduced-transparency: reduce)": dark.glassFallback,
  },
  glassChrome: {
    default: dark.glassChrome,
    "@supports not (backdrop-filter: blur(1px))": dark.glassFallback,
    "@media (prefers-reduced-transparency: reduce)": dark.glassFallback,
  },
  glassOverlay: {
    default: dark.glassOverlay,
    "@supports not (backdrop-filter: blur(1px))": dark.glassFallback,
    "@media (prefers-reduced-transparency: reduce)": dark.glassFallback,
  },
  glassFallback: dark.glassFallback,
  glassBorder: dark.glassBorder,
  glassHighlight: dark.glassHighlight,
  scrim: dark.scrim,
  userBubble: dark.userBubble,
  userBubbleBorder: dark.userBubbleBorder,
});

export const materials = stylex.defineVars({
  subtle: {
    default: "blur(18px) saturate(150%)",
    "@supports not (backdrop-filter: blur(1px))": "none",
    "@media (prefers-reduced-transparency: reduce)": "none",
  },
  chrome: {
    default: "blur(28px) saturate(165%)",
    "@supports not (backdrop-filter: blur(1px))": "none",
    "@media (prefers-reduced-transparency: reduce)": "none",
  },
  overlay: {
    default: "blur(36px) saturate(175%)",
    "@supports not (backdrop-filter: blur(1px))": "none",
    "@media (prefers-reduced-transparency: reduce)": "none",
  },
});

export const motion = stylex.defineVars({
  fast: "140ms",
  standard: "220ms",
  slow: "340ms",
  easing: "cubic-bezier(0.16, 1, 0.3, 1)",
});

export const radii = stylex.defineVars({
  small: "10px",
  medium: "14px",
  large: "20px",
  xlarge: "26px",
  pill: "999px",
});

export const shadows = stylex.defineVars({
  subtle: "0 1px 2px rgba(16, 52, 96, 0.08)",
  interactive: "0 10px 30px rgba(16, 52, 96, 0.14)",
  focus: "0 0 0 3px rgba(0, 103, 217, 0.24)",
  overlay: "0 24px 70px rgba(16, 52, 96, 0.18)",
  glass: "0 16px 44px rgba(16, 52, 96, 0.12), inset 0 1px 0 rgba(255, 255, 255, 0.72)",
  glassStrong:
    "0 28px 90px rgba(16, 52, 96, 0.20), inset 0 1px 0 rgba(255, 255, 255, 0.82)",
});

export const darkShadowsTheme = stylex.createTheme(shadows, {
  subtle: "0 1px 2px rgba(0, 0, 0, 0.28)",
  interactive: "0 12px 34px rgba(0, 0, 0, 0.32)",
  focus: "0 0 0 3px rgba(82, 168, 255, 0.30)",
  overlay: "0 28px 86px rgba(0, 0, 0, 0.42)",
  glass: "0 18px 52px rgba(0, 0, 0, 0.30), inset 0 1px 0 rgba(255, 255, 255, 0.16)",
  glassStrong:
    "0 34px 100px rgba(0, 0, 0, 0.48), inset 0 1px 0 rgba(255, 255, 255, 0.20)",
});
