import * as stylex from "@stylexjs/stylex";

type AppearancePalette = Record<string, string>;

export const appearancePalette: Record<"light" | "dark", AppearancePalette> = {
  light: {
    canvas: "#F4F7F6",
    canvasRaised: "#FAFCFB",
    surface: "#FFFFFF",
    surfaceSoft: "rgba(255, 255, 255, 0.54)",
    surfaceStrong: "#E3ECE9",
    ink: "#12201E",
    body: "#334A46",
    muted: "#5A6C69",
    subtle: "#748481",
    border: "#CBD8D5",
    borderStrong: "#AEBFBB",
    primary: "#0F766E",
    primaryHover: "#0B665F",
    primaryPressed: "#09564F",
    primarySoft: "rgba(15, 118, 110, 0.10)",
    primarySoftHover: "rgba(15, 118, 110, 0.16)",
    onPrimary: "#FFFFFF",
    success: "#087D5B",
    successSoft: "#DFF6ED",
    danger: "#C7253E",
    dangerHover: "#A91D34",
    dangerSoft: "#FFF0F3",
    dangerSoftHover: "#FFE1E7",
    dangerOnDark: "#C7253E",
    dangerOnDarkSoft: "rgba(199, 37, 62, 0.12)",
    warning: "#8A5000",
    warningHover: "#713F00",
    warningSoft: "#FFF5DC",
    warningSoftHover: "#FFE9B4",
    dark: "#0B1110",
    darkRaised: "#15201E",
    onDark: "#E8F3F0",
    onDarkMuted: "#A7B9B5",
    focus: "#0F766E",
    canvasAmbient:
      "radial-gradient(circle at 14% 0%, rgba(94, 234, 212, 0.13), transparent 32%), radial-gradient(circle at 88% 10%, rgba(157, 190, 181, 0.18), transparent 30%), #F4F7F6",
    glassSubtle: "rgba(255, 255, 255, 0.48)",
    glassChrome: "rgba(248, 251, 255, 0.64)",
    glassOverlay: "rgba(250, 252, 255, 0.82)",
    glassFallback: "#FAFCFB",
    glassBorder: "rgba(83, 112, 105, 0.22)",
    glassHighlight: "rgba(255, 255, 255, 0.78)",
    scrim: "rgba(14, 30, 27, 0.48)",
    userBubble: "rgba(220, 239, 234, 0.88)",
    userBubbleBorder: "rgba(15, 118, 110, 0.16)",
  },
  dark: {
    canvas: "#0B1110",
    canvasRaised: "#101917",
    surface: "#14201E",
    surfaceSoft: "rgba(28, 43, 40, 0.62)",
    surfaceStrong: "#23332F",
    ink: "#E8F3F0",
    body: "#CFDDD9",
    muted: "#A7B9B5",
    subtle: "#849791",
    border: "#324641",
    borderStrong: "#465C56",
    primary: "#5EEAD4",
    primaryHover: "#81F0DE",
    primaryPressed: "#3ED8C0",
    primarySoft: "rgba(94, 234, 212, 0.14)",
    primarySoftHover: "rgba(94, 234, 212, 0.22)",
    onPrimary: "#071411",
    success: "#4DD6A8",
    successSoft: "rgba(77, 214, 168, 0.14)",
    danger: "#FF6B81",
    dangerHover: "#FF8A9B",
    dangerSoft: "rgba(255, 107, 129, 0.13)",
    dangerSoftHover: "rgba(255, 107, 129, 0.22)",
    dangerOnDark: "#FF8A9B",
    dangerOnDarkSoft: "rgba(255, 107, 129, 0.16)",
    warning: "#F5B94C",
    warningHover: "#FFCA68",
    warningSoft: "rgba(245, 185, 76, 0.14)",
    warningSoftHover: "rgba(245, 185, 76, 0.22)",
    dark: "#07100E",
    darkRaised: "#14201E",
    onDark: "#E8F3F0",
    onDarkMuted: "#A7B9B5",
    focus: "#5EEAD4",
    canvasAmbient:
      "radial-gradient(circle at 12% 0%, rgba(94, 234, 212, 0.16), transparent 34%), radial-gradient(circle at 88% 8%, rgba(75, 115, 105, 0.18), transparent 30%), #0B1110",
    glassSubtle: "rgba(16, 28, 25, 0.48)",
    glassChrome: "rgba(15, 25, 23, 0.64)",
    glassOverlay: "rgba(13, 23, 21, 0.82)",
    glassFallback: "#14201E",
    glassBorder: "rgba(255, 255, 255, 0.14)",
    glassHighlight: "rgba(255, 255, 255, 0.18)",
    scrim: "rgba(0, 0, 0, 0.58)",
    userBubble: "rgba(94, 234, 212, 0.14)",
    userBubbleBorder: "rgba(94, 234, 212, 0.28)",
  },
};

const light = appearancePalette.light;
const dark = appearancePalette.dark;

export const colors = stylex.defineVars({
  canvas: light.canvas,
  canvasRaised: light.canvasRaised,
  surface: light.surface,
  surfaceSoft: light.surfaceSoft,
  surfaceStrong: light.surfaceStrong,
  ink: light.ink,
  body: light.body,
  muted: light.muted,
  subtle: light.subtle,
  border: light.border,
  borderStrong: light.borderStrong,
  primary: light.primary,
  primaryHover: light.primaryHover,
  primaryPressed: light.primaryPressed,
  primarySoft: light.primarySoft,
  primarySoftHover: light.primarySoftHover,
  onPrimary: light.onPrimary,
  success: light.success,
  successSoft: light.successSoft,
  danger: light.danger,
  dangerHover: light.dangerHover,
  dangerSoft: light.dangerSoft,
  dangerSoftHover: light.dangerSoftHover,
  dangerOnDark: light.dangerOnDark,
  dangerOnDarkSoft: light.dangerOnDarkSoft,
  warning: light.warning,
  warningHover: light.warningHover,
  warningSoft: light.warningSoft,
  warningSoftHover: light.warningSoftHover,
  dark: light.dark,
  darkRaised: light.darkRaised,
  onDark: light.onDark,
  onDarkMuted: light.onDarkMuted,
  focus: light.focus,
  canvasAmbient: light.canvasAmbient,
  glassSubtle: {
    default: light.glassSubtle,
    "@supports not (backdrop-filter: blur(1px))": light.glassFallback,
    "@media (prefers-reduced-transparency: reduce)": light.glassFallback,
  },
  glassChrome: {
    default: light.glassChrome,
    "@supports not (backdrop-filter: blur(1px))": light.glassFallback,
    "@media (prefers-reduced-transparency: reduce)": light.glassFallback,
  },
  glassOverlay: {
    default: light.glassOverlay,
    "@supports not (backdrop-filter: blur(1px))": light.glassFallback,
    "@media (prefers-reduced-transparency: reduce)": light.glassFallback,
  },
  glassFallback: light.glassFallback,
  glassBorder: light.glassBorder,
  glassHighlight: light.glassHighlight,
  scrim: light.scrim,
  userBubble: light.userBubble,
  userBubbleBorder: light.userBubbleBorder,
});

export const darkColorsTheme = stylex.createTheme(colors, {
  canvas: dark.canvas,
  canvasRaised: dark.canvasRaised,
  surface: dark.surface,
  surfaceSoft: dark.surfaceSoft,
  surfaceStrong: dark.surfaceStrong,
  ink: dark.ink,
  body: dark.body,
  muted: dark.muted,
  subtle: dark.subtle,
  border: dark.border,
  borderStrong: dark.borderStrong,
  primary: dark.primary,
  primaryHover: dark.primaryHover,
  primaryPressed: dark.primaryPressed,
  primarySoft: dark.primarySoft,
  primarySoftHover: dark.primarySoftHover,
  onPrimary: dark.onPrimary,
  success: dark.success,
  successSoft: dark.successSoft,
  danger: dark.danger,
  dangerHover: dark.dangerHover,
  dangerSoft: dark.dangerSoft,
  dangerSoftHover: dark.dangerSoftHover,
  dangerOnDark: dark.dangerOnDark,
  dangerOnDarkSoft: dark.dangerOnDarkSoft,
  warning: dark.warning,
  warningHover: dark.warningHover,
  warningSoft: dark.warningSoft,
  warningSoftHover: dark.warningSoftHover,
  dark: dark.dark,
  darkRaised: dark.darkRaised,
  onDark: dark.onDark,
  onDarkMuted: dark.onDarkMuted,
  focus: dark.focus,
  canvasAmbient: dark.canvasAmbient,
  glassSubtle: {
    default: dark.glassSubtle,
    "@supports not (backdrop-filter: blur(1px))": dark.glassFallback,
    "@media (prefers-reduced-transparency: reduce)": dark.glassFallback,
  },
  glassChrome: {
    default: dark.glassChrome,
    "@supports not (backdrop-filter: blur(1px))": dark.glassFallback,
    "@media (prefers-reduced-transparency: reduce)": dark.glassFallback,
  },
  glassOverlay: {
    default: dark.glassOverlay,
    "@supports not (backdrop-filter: blur(1px))": dark.glassFallback,
    "@media (prefers-reduced-transparency: reduce)": dark.glassFallback,
  },
  glassFallback: dark.glassFallback,
  glassBorder: dark.glassBorder,
  glassHighlight: dark.glassHighlight,
  scrim: dark.scrim,
  userBubble: dark.userBubble,
  userBubbleBorder: dark.userBubbleBorder,
});

export const materials = stylex.defineVars({
  subtle: {
    default: "blur(18px) saturate(150%)",
    "@supports not (backdrop-filter: blur(1px))": "none",
    "@media (prefers-reduced-transparency: reduce)": "none",
  },
  chrome: {
    default: "blur(28px) saturate(165%)",
    "@supports not (backdrop-filter: blur(1px))": "none",
    "@media (prefers-reduced-transparency: reduce)": "none",
  },
  overlay: {
    default: "blur(36px) saturate(175%)",
    "@supports not (backdrop-filter: blur(1px))": "none",
    "@media (prefers-reduced-transparency: reduce)": "none",
  },
});

export const motion = stylex.defineVars({
  fast: "140ms",
  standard: "220ms",
  slow: "340ms",
  easing: "cubic-bezier(0.16, 1, 0.3, 1)",
});

export const radii = stylex.defineVars({
  small: "10px",
  medium: "14px",
  large: "20px",
  xlarge: "26px",
  pill: "999px",
});

export const shadows = stylex.defineVars({
  subtle: "0 1px 2px rgba(25, 65, 57, 0.08)",
  interactive: "0 10px 30px rgba(25, 65, 57, 0.14)",
  focus: "0 0 0 3px rgba(15, 118, 110, 0.20)",
  overlay: "0 24px 70px rgba(25, 65, 57, 0.18)",
  glass: "0 16px 44px rgba(25, 65, 57, 0.12), inset 0 1px 0 rgba(255, 255, 255, 0.72)",
  glassStrong:
    "0 28px 90px rgba(25, 65, 57, 0.20), inset 0 1px 0 rgba(255, 255, 255, 0.82)",
});

export const darkShadowsTheme = stylex.createTheme(shadows, {
  subtle: "0 1px 2px rgba(0, 0, 0, 0.28)",
  interactive: "0 12px 34px rgba(0, 0, 0, 0.32)",
  focus: "0 0 0 3px rgba(94, 234, 212, 0.24)",
  overlay: "0 28px 86px rgba(0, 0, 0, 0.42)",
  glass: "0 18px 52px rgba(0, 0, 0, 0.30), inset 0 1px 0 rgba(255, 255, 255, 0.16)",
  glassStrong:
    "0 34px 100px rgba(0, 0, 0, 0.48), inset 0 1px 0 rgba(255, 255, 255, 0.20)",
});
